---
# This playbook uses "install-docker-on-ubuntu" role to install docker on Ubuntu environment
- name: Install docker on Ubuntu and Deploy web Server
  hosts: target1
  become: yes
  gather_facts: yes
  tasks:
    - name: calling role.
      include_role:
        name: install_docker_on_ubuntu

    - name: Make sure docker-compose is installed
      pip: 
        name: docker-compose
        state: present
    
    - name: Copy docker folder to managed host
      git: 
        repo: https://github.com/mahadevaprasadap/ansible-docker.git
        dest: /tmp/ansible-docker
        separate_git_dir: /tmp/ansible-docker.git

    - name: Deploy containers using docker-compose command
      docker_compose: 
        project_src: /tmp/ansible-docker/docker
        build: yes
        scale: 
          flask: 2
        state: present