# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes: 
      - my_vol:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    depends_on:
      - "mongo"
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  flask:
    build: 
      context: ./app
    restart: always
    depends_on:
      - "mongo"
    environment:
      MONGO_USER: root
      MONGO_PASSWORD: example
      MONGO_DB_NAME: todo
      MONGO_COLLECTION: todos
      MONGO_HOST: mongo

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - 80:80
    depends_on: 
      - flask

volumes:
  my_vol:

